% generate function skeletons exploiting the proto file generated by
%  loadlibrary(), as a first basis for further editing
loadlibrary('libASICamera2','ASICamera2.h','mfilename','mxproto');
unloadlibrary('libASICamera2');

[methodinfo,structs,enuminfo,ThunkLibName]=mxproto;

for i=1:length(methodinfo.name)
    filename=fullfile('..','..','..','wrappers',[methodinfo.name{i} '.m']);    
    if ~isfile(filename)
    % don't overwrite existing files
        fid=fopen(filename,'w');
        fprintf(fid,'function [ret,]=%s()\n',methodinfo.name{i});
        fprintf(fid,'%% automatically generated parsing ASICamera2.h\n');
        fprintf(fid,'%% Only useful as a template, remove comment when fixed\n');
        fprintf(fid,'    [ret,]=calllib(''libASICamera2'',''%s'',);\n',methodinfo.name{i});
        fprintf(fid,'    ret=inst.ASI_ERROR_CODE(ret);\n');
        fclose(fid);
    end
end