% generate enum classes exploiting the proto file generated by
%  loadlibrary()
loadlibrary('libASICamera2','ASICamera2.h','mfilename','mxproto');
unloadlibrary('libASICamera2');

[methodinfo,structs,enuminfo,ThunkLibName]=mxproto;

enumclass=fields(enuminfo);
for i=1:length(enumclass)
    
    values=fields(enuminfo.(enumclass{i}));
    filename=fullfile('..','..',[enumclass{i} '.m']);
    
    fid=fopen(filename,'w');
    fprintf(fid,'classdef %s < uint8\n',enumclass{i});
    fprintf(fid,'%% automatically generated parsing ASICamera2.h\n');
    fprintf(fid,'    enumeration\n');
    for k=1:length(values)
        fprintf(fid,'        %s (%d)\n',values{k},enuminfo.(enumclass{i}).(values{k}));
    end
    fprintf(fid,'    end\n');
    fprintf(fid,'end\n');
    fclose(fid);
end